coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 90%

comment:
  layout: "reach, diff, flags, components"
  behavior: default
  require_changes: false
