"""AuthFort — Authentication and authorization library for Python."""

__version__ = "0.0.28"

from authfort.alembic_helper import alembic_filters, register_foreign_tables
from authfort.authfort import AuthFort
from authfort.config import CookieConfig, RateLimitConfig
from authfort.core.errors import AuthError
from authfort.core.schemas import AuthResponse, AuthTokens, ListUsersResponse, MFAChallenge, MFASetup, MFAStatus, SessionResponse, UserResponse
from authfort.events import (
    BackupCodeUsed,
    BackupCodesRegenerated,
    EmailOTPLogin,
    EmailOTPRequested,
    EmailVerificationRequested,
    EmailVerified,
    KeyRotated,
    Login,
    LoginFailed,
    Logout,
    MFADisabled,
    MFAEnabled,
    MFAFailed,
    MFALogin,
    MagicLinkLogin,
    MagicLinkRequested,
    OAuthLink,
    PasswordChanged,
    PasswordPwnedRejected,
    PasswordReset,
    PasswordResetRequested,
    PasswordReuseRejected,
    PasswordSet,
    RateLimitExceeded,
    RefreshTokenMismatch,
    RoleAdded,
    RoleRemoved,
    SessionRevoked,
    TokenRefreshed,
    UserBanned,
    UserCreated,
    UserDeleted,
    UserUnbanned,
    UserUpdated,
)
from authfort.models.user import User as AuthUser
from authfort.models.user_role import UserRole as AuthUserRole
from authfort.providers.generic import GenericOAuthProvider, GenericOIDCProvider
from authfort.providers.github import GitHubProvider
from authfort.providers.google import GoogleProvider

__all__ = [
    "AuthFort",
    "AuthError",
    "AuthUser",
    "AuthUserRole",
    "AuthResponse",
    "AuthTokens",
    "BackupCodeUsed",
    "BackupCodesRegenerated",
    "CookieConfig",
    "EmailOTPLogin",
    "EmailOTPRequested",
    "EmailVerificationRequested",
    "EmailVerified",
    "GenericOAuthProvider",
    "GenericOIDCProvider",
    "GoogleProvider",
    "GitHubProvider",
    "KeyRotated",
    "ListUsersResponse",
    "Login",
    "LoginFailed",
    "Logout",
    "MFAChallenge",
    "MFADisabled",
    "MFAEnabled",
    "MFAFailed",
    "MFALogin",
    "MFASetup",
    "MFAStatus",
    "MagicLinkLogin",
    "MagicLinkRequested",
    "OAuthLink",
    "PasswordChanged",
    "PasswordPwnedRejected",
    "PasswordReset",
    "PasswordResetRequested",
    "PasswordReuseRejected",
    "PasswordSet",
    "RateLimitConfig",
    "RateLimitExceeded",
    "RefreshTokenMismatch",
    "RoleAdded",
    "RoleRemoved",
    "SessionResponse",
    "SessionRevoked",
    "TokenRefreshed",
    "UserBanned",
    "UserCreated",
    "UserDeleted",
    "UserResponse",
    "UserUnbanned",
    "UserUpdated",
    "alembic_filters",
    "register_foreign_tables",
]
